/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.groupf.java.swing.m7.interfaces;

/**
 *
 * @author admin
 */
public class GuiCuiner extends javax.swing.JFrame {

    /**
     * Creates new form GuiCuiner
     */
    public GuiCuiner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCuina = new javax.swing.JPanel();
        jLabelCuina = new javax.swing.JLabel();
        jScrollPanepostres = new javax.swing.JScrollPane();
        jTablePostres = new javax.swing.JTable();
        jScrollPanePrimers = new javax.swing.JScrollPane();
        jTablePrimers = new javax.swing.JTable();
        jScrollPaneSegons = new javax.swing.JScrollPane();
        jTableSegons = new javax.swing.JTable();
        jLabelSegons = new javax.swing.JLabel();
        jLabelPrimers = new javax.swing.JLabel();
        jLabelPostres = new javax.swing.JLabel();
        jButtonPreparar = new javax.swing.JButton();
        jButtonSortir = new javax.swing.JButton();
        jButtonFet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCuina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCuina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCuina.setText("Cuina");

        jTablePostres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTablePostres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Taula", "Plat", "Temps", "Estat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePostres.setColumnSelectionAllowed(true);
        jTablePostres.getTableHeader().setReorderingAllowed(false);
        jScrollPanepostres.setViewportView(jTablePostres);
        jTablePostres.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTablePostres.getColumnModel().getColumnCount() > 0) {
            jTablePostres.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTablePostres.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTablePostres.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jTablePrimers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTablePrimers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Taula", "Plat", "Temps", "Estat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePrimers.getTableHeader().setReorderingAllowed(false);
        jScrollPanePrimers.setViewportView(jTablePrimers);
        jTablePrimers.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTablePrimers.getColumnModel().getColumnCount() > 0) {
            jTablePrimers.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTablePrimers.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTablePrimers.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jTableSegons.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableSegons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Taula", "Plat", "Temps", "Estat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSegons.getTableHeader().setReorderingAllowed(false);
        jScrollPaneSegons.setViewportView(jTableSegons);
        jTableSegons.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableSegons.getColumnModel().getColumnCount() > 0) {
            jTableSegons.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTableSegons.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTableSegons.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jLabelSegons.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSegons.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSegons.setText("Segons");

        jLabelPrimers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrimers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrimers.setText("Primers");

        jLabelPostres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPostres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPostres.setText("Postres");

        jButtonPreparar.setBackground(new java.awt.Color(255, 255, 51));
        jButtonPreparar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonPreparar.setText("Preparar");

        jButtonSortir.setBackground(new java.awt.Color(52, 167, 251));
        jButtonSortir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSortir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSortir.setText("Sortir");

        jButtonFet.setBackground(new java.awt.Color(51, 255, 51));
        jButtonFet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonFet.setText("Fet");

        javax.swing.GroupLayout jPanelCuinaLayout = new javax.swing.GroupLayout(jPanelCuina);
        jPanelCuina.setLayout(jPanelCuinaLayout);
        jPanelCuinaLayout.setHorizontalGroup(
            jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCuina, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCuinaLayout.createSequentialGroup()
                .addGroup(jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCuinaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneSegons, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPanePrimers, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCuinaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSegons, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrimers, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelPostres, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                        .addComponent(jScrollPanepostres, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                        .addComponent(jButtonPreparar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonFet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSortir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanelCuinaLayout.setVerticalGroup(
            jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCuinaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelCuina)
                .addGap(22, 22, 22)
                .addGroup(jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPostres)
                    .addComponent(jLabelPrimers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPanepostres, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPanePrimers, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabelSegons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCuinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCuinaLayout.createSequentialGroup()
                        .addComponent(jButtonPreparar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButtonFet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneSegons, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCuina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCuina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCuiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCuiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCuiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCuiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCuiner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFet;
    private javax.swing.JButton jButtonPreparar;
    private javax.swing.JButton jButtonSortir;
    private javax.swing.JLabel jLabelCuina;
    private javax.swing.JLabel jLabelPostres;
    private javax.swing.JLabel jLabelPrimers;
    private javax.swing.JLabel jLabelSegons;
    private javax.swing.JPanel jPanelCuina;
    private javax.swing.JScrollPane jScrollPanePrimers;
    private javax.swing.JScrollPane jScrollPaneSegons;
    private javax.swing.JScrollPane jScrollPanepostres;
    private javax.swing.JTable jTablePostres;
    private javax.swing.JTable jTablePrimers;
    private javax.swing.JTable jTableSegons;
    // End of variables declaration//GEN-END:variables
}
